# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a97bbdb8573c00de783116638676012515c76938bbed2ea965257764088cae7e6c04de26c9e00a194ce33cbb54391027cc8c47be56b7c8add89a694febfbdc2

test:
  secret_key_base: 99775f6b10081c66d8165ac7c61416fe515dc8ee868b48188cf39f10c5404091f8df464cd47de38eed2829a0e47167730909fdc36ed25f480f9b926861fca84d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
